export const SkinsList = [
  {
    id: "obsidian",
    image: {
      imageOne: require("@/public/images/skins/obsidian/profile.png"),
      imageTwo: require("@/public/images/skins/obsidian/voice_activity_week.png"),
      imageThree: require("@/public/images/skins/obsidian/voice_activity_month.png"),
      imageFour: require("@/public/images/skins/obsidian/monthly_statistics.png"),
      imageFive: require("@/public/images/skins/obsidian/leaderboard_list.png"),
      imageSix: require("@/public/images/skins/obsidian/leaderboard_top.png"),
      imageSeven: require("@/public/images/skins/obsidian/todo_profile.png"),
      imageEight: require("@/public/images/skins/obsidian/todo_tasks.png"),
      imageOneThumbnail: require("@/public/images/skins/obsidian/thumbnails/profile.png"),
      imageTwoThumbnail: require("@/public/images/skins/obsidian/thumbnails/voice_activity_week.png"),
      imageThreeThumbnail: require("@/public/images/skins/obsidian/thumbnails/voice_activity_month.png"),
      imageFourThumbnail: require("@/public/images/skins/obsidian/thumbnails/monthly_statistics.png"),
      imageFiveThumbnail: require("@/public/images/skins/obsidian/thumbnails/leaderboard_list.png"),
      imageSixThumbnail: require("@/public/images/skins/obsidian/thumbnails/leaderboard_top.png"),
      imageSevenThumbnail: require("@/public/images/skins/obsidian/thumbnails/todo_profile.png"),
      imageEightThumbnail: require("@/public/images/skins/obsidian/thumbnails/todo_tasks.png"),
    },
    label: "Obsidian",
    price: 1500,
  },
  {
    id: "platinum",
    image: {
      imageOne: require("@/public/images/skins/platinum/profile.png"),
      imageTwo: require("@/public/images/skins/platinum/voice_activity_week.png"),
      imageThree: require("@/public/images/skins/platinum/voice_activity_month.png"),
      imageFour: require("@/public/images/skins/platinum/monthly_statistics.png"),
      imageFive: require("@/public/images/skins/platinum/leaderboard_list.png"),
      imageSix: require("@/public/images/skins/platinum/leaderboard_top.png"),
      imageSeven: require("@/public/images/skins/platinum/todo_profile.png"),
      imageEight: require("@/public/images/skins/platinum/todo_tasks.png"),
      imageOneThumbnail: require("@/public/images/skins/platinum/thumbnails/profile.png"),
      imageTwoThumbnail: require("@/public/images/skins/platinum/thumbnails/voice_activity_week.png"),
      imageThreeThumbnail: require("@/public/images/skins/platinum/thumbnails/voice_activity_month.png"),
      imageFourThumbnail: require("@/public/images/skins/platinum/thumbnails/monthly_statistics.png"),
      imageFiveThumbnail: require("@/public/images/skins/platinum/thumbnails/leaderboard_list.png"),
      imageSixThumbnail: require("@/public/images/skins/platinum/thumbnails/leaderboard_top.png"),
      imageSevenThumbnail: require("@/public/images/skins/platinum/thumbnails/todo_profile.png"),
      imageEightThumbnail: require("@/public/images/skins/platinum/thumbnails/todo_tasks.png"),
    },
    label: "Platinum",
    price: 1500,
  },
  {
    id: "blue_bayoux",
    image: {
      imageOne: require("@/public/images/skins/blue_bayoux/profile.png"),
      imageTwo: require("@/public/images/skins/blue_bayoux/voice_activity_week.png"),
      imageThree: require("@/public/images/skins/blue_bayoux/voice_activity_month.png"),
      imageFour: require("@/public/images/skins/blue_bayoux/monthly_statistics.png"),
      imageFive: require("@/public/images/skins/blue_bayoux/leaderboard_list.png"),
      imageSix: require("@/public/images/skins/blue_bayoux/leaderboard_top.png"),
      imageSeven: require("@/public/images/skins/blue_bayoux/todo_profile.png"),
      imageEight: require("@/public/images/skins/blue_bayoux/todo_tasks.png"),
      imageOneThumbnail: require("@/public/images/skins/blue_bayoux/thumbnails/profile.png"),
      imageTwoThumbnail: require("@/public/images/skins/blue_bayoux/thumbnails/voice_activity_week.png"),
      imageThreeThumbnail: require("@/public/images/skins/blue_bayoux/thumbnails/voice_activity_month.png"),
      imageFourThumbnail: require("@/public/images/skins/blue_bayoux/thumbnails/monthly_statistics.png"),
      imageFiveThumbnail: require("@/public/images/skins/blue_bayoux/thumbnails/leaderboard_list.png"),
      imageSixThumbnail: require("@/public/images/skins/blue_bayoux/thumbnails/leaderboard_top.png"),
      imageSevenThumbnail: require("@/public/images/skins/blue_bayoux/thumbnails/todo_profile.png"),
      imageEightThumbnail: require("@/public/images/skins/blue_bayoux/thumbnails/todo_tasks.png"),
    },
    label: "Blue Bayoux",
    price: 1500,
  },
  {
    id: "boston_blue",
    image: {
      imageOne: require("@/public/images/skins/boston_blue/profile.png"),
      imageTwo: require("@/public/images/skins/boston_blue/voice_activity_week.png"),
      imageThree: require("@/public/images/skins/boston_blue/voice_activity_month.png"),
      imageFour: require("@/public/images/skins/boston_blue/monthly_statistics.png"),
      imageFive: require("@/public/images/skins/boston_blue/leaderboard_list.png"),
      imageSix: require("@/public/images/skins/boston_blue/leaderboard_top.png"),
      imageSeven: require("@/public/images/skins/boston_blue/todo_profile.png"),
      imageEight: require("@/public/images/skins/boston_blue/todo_tasks.png"),
      imageOneThumbnail: require("@/public/images/skins/boston_blue/thumbnails/profile.png"),
      imageTwoThumbnail: require("@/public/images/skins/boston_blue/thumbnails/voice_activity_week.png"),
      imageThreeThumbnail: require("@/public/images/skins/boston_blue/thumbnails/voice_activity_month.png"),
      imageFourThumbnail: require("@/public/images/skins/boston_blue/thumbnails/monthly_statistics.png"),
      imageFiveThumbnail: require("@/public/images/skins/boston_blue/thumbnails/leaderboard_list.png"),
      imageSixThumbnail: require("@/public/images/skins/boston_blue/thumbnails/leaderboard_top.png"),
      imageSevenThumbnail: require("@/public/images/skins/boston_blue/thumbnails/todo_profile.png"),
      imageEightThumbnail: require("@/public/images/skins/boston_blue/thumbnails/todo_tasks.png"),
    },
    label: "Boston Blue",
    price: 750,
  },
  {
    id: "bubble_gum",
    image: {
      imageOne: require("@/public/images/skins/bubble_gum/profile.png"),
      imageTwo: require("@/public/images/skins/bubble_gum/voice_activity_week.png"),
      imageThree: require("@/public/images/skins/bubble_gum/voice_activity_month.png"),
      imageFour: require("@/public/images/skins/bubble_gum/monthly_statistics.png"),
      imageFive: require("@/public/images/skins/bubble_gum/leaderboard_list.png"),
      imageSix: require("@/public/images/skins/bubble_gum/leaderboard_top.png"),
      imageSeven: require("@/public/images/skins/bubble_gum/todo_profile.png"),
      imageEight: require("@/public/images/skins/bubble_gum/todo_tasks.png"),
      imageOneThumbnail: require("@/public/images/skins/bubble_gum/thumbnails/profile.png"),
      imageTwoThumbnail: require("@/public/images/skins/bubble_gum/thumbnails/voice_activity_week.png"),
      imageThreeThumbnail: require("@/public/images/skins/bubble_gum/thumbnails/voice_activity_month.png"),
      imageFourThumbnail: require("@/public/images/skins/bubble_gum/thumbnails/monthly_statistics.png"),
      imageFiveThumbnail: require("@/public/images/skins/bubble_gum/thumbnails/leaderboard_list.png"),
      imageSixThumbnail: require("@/public/images/skins/bubble_gum/thumbnails/leaderboard_top.png"),
      imageSevenThumbnail: require("@/public/images/skins/bubble_gum/thumbnails/todo_profile.png"),
      imageEightThumbnail: require("@/public/images/skins/bubble_gum/thumbnails/todo_tasks.png"),
    },
    label: "Bubble Gum",
    price: 1500,
  },
  {
    id: "cotton_candy",
    image: {
      imageOne: require("@/public/images/skins/cotton_candy/profile.png"),
      imageTwo: require("@/public/images/skins/cotton_candy/voice_activity_week.png"),
      imageThree: require("@/public/images/skins/cotton_candy/voice_activity_month.png"),
      imageFour: require("@/public/images/skins/cotton_candy/monthly_statistics.png"),
      imageFive: require("@/public/images/skins/cotton_candy/leaderboard_list.png"),
      imageSix: require("@/public/images/skins/cotton_candy/leaderboard_top.png"),
      imageSeven: require("@/public/images/skins/cotton_candy/todo_profile.png"),
      imageEight: require("@/public/images/skins/cotton_candy/todo_tasks.png"),
      imageOneThumbnail: require("@/public/images/skins/cotton_candy/thumbnails/profile.png"),
      imageTwoThumbnail: require("@/public/images/skins/cotton_candy/thumbnails/voice_activity_week.png"),
      imageThreeThumbnail: require("@/public/images/skins/cotton_candy/thumbnails/voice_activity_month.png"),
      imageFourThumbnail: require("@/public/images/skins/cotton_candy/thumbnails/monthly_statistics.png"),
      imageFiveThumbnail: require("@/public/images/skins/cotton_candy/thumbnails/leaderboard_list.png"),
      imageSixThumbnail: require("@/public/images/skins/cotton_candy/thumbnails/leaderboard_top.png"),
      imageSevenThumbnail: require("@/public/images/skins/cotton_candy/thumbnails/todo_profile.png"),
      imageEightThumbnail: require("@/public/images/skins/cotton_candy/thumbnails/todo_tasks.png"),
    },
    label: "Cotton Candy",
    price: 1500,
  },
];

