export const SkinsList = [
  {
    id: "obsidian",
    image: {
      imageOne: require("@/public/images/skins/obsidian/profile.png"),
      imageTwo: require("@/public/images/skins/obsidian/voice_activity_week.png"),
      imageThree: require("@/public/images/skins/obsidian/voice_activity_month.png"),
      imageFour: require("@/public/images/skins/obsidian/monthly_statistics.png"),
      imageFive: require("@/public/images/skins/obsidian/leaderboard_list.png"),
      imageSix: require("@/public/images/skins/obsidian/leaderboard_top.png"),
      imageSeven: require("@/public/images/skins/obsidian/todo_profile.png"),
      imageEight: require("@/public/images/skins/obsidian/todo_tasks.png"),
      imageOneThumbnail: require("@/public/images/skins/obsidian/thumbnails/profile.png"),
      imageTwoThumbnail: require("@/public/images/skins/obsidian/thumbnails/voice_activity_week.png"),
      imageThreeThumbnail: require("@/public/images/skins/obsidian/thumbnails/voice_activity_month.png"),
      imageFourThumbnail: require("@/public/images/skins/obsidian/thumbnails/monthly_statistics.png"),
      imageFiveThumbnail: require("@/public/images/skins/obsidian/thumbnails/leaderboard_list.png"),
      imageSixThumbnail: require("@/public/images/skins/obsidian/thumbnails/leaderboard_top.png"),
      imageSevenThumbnail: require("@/public/images/skins/obsidian/thumbnails/todo_profile.png"),
      imageEightThumbnail: require("@/public/images/skins/obsidian/thumbnails/todo_tasks.png"),
    },
    label: "Obsidian",
    price: 1500,
  },
  {
    id: "platinum",
    image: {
      imageOne: require("@/public/images/skins/platinum/profile.png"),
      imageTwo: require("@/public/images/skins/platinum/voice_activity_week.png"),
      imageThree: require("@/public/images/skins/platinum/voice_activity_month.png"),
      imageFour: require("@/public/images/skins/platinum/monthly_statistics.png"),
      imageFive: require("@/public/images/skins/platinum/leaderboard_list.png"),
      imageSix: require("@/public/images/skins/platinum/leaderboard_top.png"),
      imageSeven: require("@/public/images/skins/platinum/todo_profile.png"),
      imageEight: require("@/public/images/skins/platinum/todo_tasks.png"),
      imageOneThumbnail: require("@/public/images/skins/platinum/thumbnails/profile.png"),
      imageTwoThumbnail: require("@/public/images/skins/platinum/thumbnails/voice_activity_week.png"),
      imageThreeThumbnail: require("@/public/images/skins/platinum/thumbnails/voice_activity_month.png"),
      imageFourThumbnail: require("@/public/images/skins/platinum/thumbnails/monthly_statistics.png"),
      imageFiveThumbnail: require("@/public/images/skins/platinum/thumbnails/leaderboard_list.png"),
      imageSixThumbnail: require("@/public/images/skins/platinum/thumbnails/leaderboard_top.png"),
      imageSevenThumbnail: require("@/public/images/skins/platinum/thumbnails/todo_profile.png"),
      imageEightThumbnail: require("@/public/images/skins/platinum/thumbnails/todo_tasks.png"),
    },
    label: "Platinum",
    price: 750,
  },
];

