// ============================================================
// AI-GENERATED FILE
// Created: 2026-03-14
// Purpose: Default color values for all bot skins per card type.
//          Extracted from bot's skin.json files + Python ColourField defaults.
// ============================================================

type SkinDefaults = Record<string, Record<string, Record<string, string>>>

const SKIN_DEFAULTS: SkinDefaults = {
  original: {
    profile: { header_colour_1: "#DDB21D", header_colour_2: "#BABABA", subheader_colour: "#DDB21D", badge_text_colour: "#FFFFFF", badge_blob_colour: "#1473A2", rank_name_colour: "#DDB21D", rank_hours_colour: "#FFFFFF", next_rank_colour: "#FFFFFF", bar_full_colour: "#DDB21D", bar_empty_colour: "#2F4858", counter_colour: "#FFFFFF", counter_bg_colour: "#515B8D60" },
    stats: { header_colour: "#DDB21D", stats_subheader_colour: "#FFFFFF", stats_text_colour: "#BABABA", col2_date_colour: "#FFFFFF", col2_hours_colour: "#1473A2", cal_weekday_colour: "#FFFFFF", cal_number_colour: "#BABABA", cal_number_end_colour: "#BABABA", cal_streak_middle_colour: "#1B3343", cal_streak_end_colour: "#1473A2" },
    weekly_stats: { title_colour: "#DDB21D", top_hours_colour: "#FFFFFF", top_weekday_colour: "#FFFFFF", top_date_colour: "#808080", top_this_colour: "#DDB21D", top_last_colour: "#377689CC", btm_weekday_colour: "#FFFFFF", btm_day_colour: "#FFFFFF", btm_this_colour: "#DDB21D", btm_last_colour: "#5E6C747F", btm_bar_horiz_colour: "#052B3B93", this_week_colour: "#BABABA", last_week_colour: "#BABABA", footer_colour: "#6F6E6F" },
    monthly_stats: { title_colour: "#DDB21D", top_hours_colour: "#FFFFFF", top_hours_bg_colour: "#0B465E", top_date_colour: "#FFFFFF", top_line_colour: "#042231", top_this_colour: "#DDB21D", top_this_hours_colour: "#DDB21D", top_last_colour: "#377689CC", top_last_hours_colour: "#5F91A1", this_month_colour: "#BABABA", last_month_colour: "#BABABA", weekday_background_colour: "#60606038", weekday_colour: "#FFFFFF", month_background_colour: "#60606038", month_colour: "#FFFFFF", stats_key_colour: "#FFFFFF", stats_value_colour: "#808080", footer_colour: "#6F6E6F" },
    weekly_goals: { title_colour: "#DDB21D", mini_profile_name_colour: "#DDB21D", mini_profile_discrim_colour: "#BABABA", mini_profile_badge_colour: "#FFFFFF", mini_profile_badge_text_colour: "#051822", progress_bg_colour: "#273341", progress_colour: "#6CB7D0", attendance_colour: "#FFFFFF", attendance_rate_colour: "#DDB21D", task_count_colour: "#DDB21D", task_done_colour: "#FFFFFF", studied_text_colour: "#FFFFFF", task_goal_colour: "#FFFFFF", studied_hour_colour: "#DDB21D", task_goal_number_colour: "#FFFFFF", task_done_number_colour: "#292828", task_undone_number_colour: "#FFFFFF", task_done_text_colour: "#686868", task_undone_text_colour: "#FFFFFF", footer_colour: "#6F6E6F" },
    monthly_goals: { title_colour: "#DDB21D", mini_profile_name_colour: "#DDB21D", mini_profile_discrim_colour: "#BABABA", mini_profile_badge_colour: "#FFFFFF", mini_profile_badge_text_colour: "#051822", progress_bg_colour: "#273341", progress_colour: "#6CB7D0", attendance_colour: "#FFFFFF", attendance_rate_colour: "#DDB21D", task_count_colour: "#DDB21D", task_done_colour: "#FFFFFF", studied_text_colour: "#FFFFFF", task_goal_colour: "#FFFFFF", studied_hour_colour: "#DDB21D", task_goal_number_colour: "#FFFFFF", task_done_number_colour: "#292828", task_undone_number_colour: "#FFFFFF", task_done_text_colour: "#686868", task_undone_text_colour: "#FFFFFF", footer_colour: "#6F6E6F" },
    leaderboard: { header_text_colour: "#DDB21D", subheader_name_colour: "#FFFFFF", subheader_value_colour: "#FFFFFF", top_position_colour: "#FFFFFF", top_name_colour: "#DDB21D", top_hours_colour: "#FFFFFF", entry_position_colour: "#FFFFFF", entry_position_highlight_colour: "#FFFFFF", entry_name_colour: "#FFFFFF", entry_hours_colour: "#FFFFFF", entry_bg_colour: "#162D3C", entry_bg_highlight_colour: "#0D4865" },
  },
  obsidian: {
    profile: { header_colour_1: "#9A9FCD", header_colour_2: "#B3B6C6", subheader_colour: "#FFFFFF", badge_text_colour: "#414A9F", badge_blob_colour: "#FFFFFF", rank_name_colour: "#FFFFFF", rank_hours_colour: "#53504D", next_rank_colour: "#53504D", bar_full_colour: "#9A9FCD", bar_empty_colour: "#9A9FCD4D", counter_colour: "#95A9D0", counter_bg_colour: "#515B8D60" },
    stats: { header_colour: "#FFFFFF", stats_subheader_colour: "#9E9E9E", stats_text_colour: "#757271", col2_date_colour: "#9E9E9E", col2_hours_colour: "#FFFFFF", cal_weekday_colour: "#FFFFFF", cal_number_colour: "#6E7877", cal_number_end_colour: "#FFFFFF", cal_streak_middle_colour: "#54548040", cal_streak_end_colour: "#545480" },
    weekly_stats: { title_colour: "#9A9FCC", top_hours_colour: "#E2E2E2", top_weekday_colour: "#9E9E9E", top_date_colour: "#9E9E9E", top_this_colour: "#8B9ACD", top_last_colour: "#3D486F80", btm_weekday_colour: "#E2E2E2", btm_day_colour: "#9E9E9E", btm_this_colour: "#8B9ACD", btm_last_colour: "#3D486F80", btm_bar_horiz_colour: "#2C33466E", this_week_colour: "#8F8F8F", last_week_colour: "#8F8F8F", footer_colour: "#555671" },
    monthly_stats: { title_colour: "#9A9FCC", top_hours_colour: "#E2E2E2", top_hours_bg_colour: "#555682", top_date_colour: "#9E9F9F", top_line_colour: "#A1ACCD26", top_this_colour: "#8081BE", top_this_hours_colour: "#8081BE", top_last_colour: "#8487A073", top_last_hours_colour: "#E3E2F1", this_month_colour: "#8F8F8F", last_month_colour: "#8F8F8F", weekday_background_colour: "#4B55A5", weekday_colour: "#E2E2E2", month_background_colour: "#4B55A5", month_colour: "#E2E2E2", stats_key_colour: "#9E9E9E", stats_value_colour: "#9E9E9E", footer_colour: "#555671" },
    weekly_goals: { title_colour: "#9A9FCC", mini_profile_name_colour: "#8282BF", mini_profile_discrim_colour: "#B9BABB", mini_profile_badge_colour: "#FFFFFF", mini_profile_badge_text_colour: "#414A9F", progress_bg_colour: "#9A9FCC40", progress_colour: "#8B9ACD", attendance_colour: "#9E9E9E", attendance_rate_colour: "#9A9FCC", task_count_colour: "#9A9FCC", task_done_colour: "#9E9E9E", studied_text_colour: "#9E9E9E", task_goal_colour: "#9E9E9E", studied_hour_colour: "#9A9FCC", task_goal_number_colour: "#9E9E9E", task_done_number_colour: "#7E6FB2", task_undone_number_colour: "#7E6FB2", task_done_text_colour: "#515151", task_undone_text_colour: "#F5F6F7", footer_colour: "#555671" },
    monthly_goals: { title_colour: "#9A9FCC", mini_profile_name_colour: "#8282BF", mini_profile_discrim_colour: "#B9BABB", mini_profile_badge_colour: "#FFFFFF", mini_profile_badge_text_colour: "#414A9F", progress_bg_colour: "#9A9FCC40", progress_colour: "#8B9ACD", attendance_colour: "#9E9E9E", attendance_rate_colour: "#9A9FCC", task_count_colour: "#9A9FCC", task_done_colour: "#9E9E9E", studied_text_colour: "#9E9E9E", task_goal_colour: "#9E9E9E", studied_hour_colour: "#9A9FCC", task_goal_number_colour: "#9E9E9E", task_done_number_colour: "#7E6FB2", task_undone_number_colour: "#7E6FB2", task_done_text_colour: "#515151", task_undone_text_colour: "#F5F6F7", footer_colour: "#555671" },
    leaderboard: { header_text_colour: "#9A9ECE", subheader_name_colour: "#767372", subheader_value_colour: "#767372", top_position_colour: "#BBBBBB", top_name_colour: "#9A9FCC", top_hours_colour: "#BBBBBB", entry_position_colour: "#BBBBBB", entry_position_highlight_colour: "#BBBBBB", entry_name_colour: "#9A9FCC", entry_hours_colour: "#BBBBBB", entry_bg_colour: "#55568233", entry_bg_highlight_colour: "#55568273" },
  },
  platinum: {
    profile: { header_colour_1: "#8685EF", header_colour_2: "#B9B9BA", subheader_colour: "#8685EF", badge_text_colour: "#E4D1FF", badge_blob_colour: "#9545FF", rank_name_colour: "#8685EF", rank_hours_colour: "#836866", next_rank_colour: "#836866", bar_full_colour: "#8685EF", bar_empty_colour: "#8685EF4D", counter_colour: "#6D6EB6", counter_bg_colour: "#515B8D60" },
    stats: { header_colour: "#8685EF", stats_subheader_colour: "#757271", stats_text_colour: "#8685EF", col2_date_colour: "#DA928C", col2_hours_colour: "#8685EF", cal_weekday_colour: "#DF8790", cal_number_colour: "#DF8790", cal_number_end_colour: "#C154DA", cal_streak_middle_colour: "#ED145240", cal_streak_end_colour: "#A3A8F3" },
    weekly_stats: { title_colour: "#8283BF", top_hours_colour: "#E2E2E2", top_weekday_colour: "#846967", top_date_colour: "#846967", top_this_colour: "#8283BF", top_last_colour: "#DF879080", btm_weekday_colour: "#846967", btm_day_colour: "#846967", btm_this_colour: "#8283BF", btm_last_colour: "#DF879080", btm_bar_horiz_colour: "#B2B8D866", this_week_colour: "#8283BF", last_week_colour: "#DF879080", footer_colour: "#9B93C7" },
    monthly_stats: { title_colour: "#8283BF", top_hours_colour: "#E2E2E2", top_hours_bg_colour: "#8283BF", top_date_colour: "#846967", top_line_colour: "#FFFFFF4D", top_this_colour: "#8283BF", top_this_hours_colour: "#8283BF", top_last_colour: "#4D484873", top_last_hours_colour: "#E3E2F1", this_month_colour: "#727374", last_month_colour: "#727374", weekday_background_colour: "#8283BF", weekday_colour: "#E2E2E2", month_background_colour: "#8283BF", month_colour: "#E2E2E2", stats_key_colour: "#727374", stats_value_colour: "#727374", footer_colour: "#9B93C7" },
    weekly_goals: { title_colour: "#8283BF", mini_profile_name_colour: "#8685EF", mini_profile_discrim_colour: "#B9B9BA", mini_profile_badge_colour: "#9545FF", mini_profile_badge_text_colour: "#E4D1FF", progress_bg_colour: "#8283BF40", progress_colour: "#8283BF", attendance_colour: "#846967", attendance_rate_colour: "#DA928C", task_count_colour: "#DA928C", task_done_colour: "#846967", studied_text_colour: "#846967", task_goal_colour: "#846967", studied_hour_colour: "#DA928C", task_goal_number_colour: "#9E9E9E", task_done_number_colour: "#7C64AC", task_undone_number_colour: "#7C64AC", task_done_text_colour: "#B3C1BF", task_undone_text_colour: "#4C4847", footer_colour: "#9B93C7" },
    monthly_goals: { title_colour: "#8283BF", mini_profile_name_colour: "#8685EF", mini_profile_discrim_colour: "#B9B9BA", mini_profile_badge_colour: "#9545FF", mini_profile_badge_text_colour: "#E4D1FF", progress_bg_colour: "#8283BF40", progress_colour: "#8283BF", attendance_colour: "#846967", attendance_rate_colour: "#DA928C", task_count_colour: "#DA928C", task_done_colour: "#846967", studied_text_colour: "#846967", task_goal_colour: "#846967", studied_hour_colour: "#DA928C", task_goal_number_colour: "#9E9E9E", task_done_number_colour: "#7C64AC", task_undone_number_colour: "#7C64AC", task_done_text_colour: "#B3C1BF", task_undone_text_colour: "#4C4847", footer_colour: "#9B93C7" },
    leaderboard: { header_text_colour: "#8283BF", subheader_name_colour: "#846967", subheader_value_colour: "#846967", top_position_colour: "#8283BF", top_name_colour: "#DA928C", top_hours_colour: "#846967", entry_position_colour: "#8283BF", entry_position_highlight_colour: "#FFFFFF", entry_name_colour: "#DA928C", entry_hours_colour: "#846967", entry_bg_colour: "#E5E5E5", entry_bg_highlight_colour: "#8283BF" },
  },
  boston_blue: {
    profile: { header_colour_1: "#1E9AC4", header_colour_2: "#2276A0", subheader_colour: "#E97BC1", badge_text_colour: "#152A4A", badge_blob_colour: "#E97BC1", rank_name_colour: "#E97BC1", rank_hours_colour: "#B4BBC5", next_rank_colour: "#B4BBC5", bar_full_colour: "#E97BC1", bar_empty_colour: "#E97BC14D", counter_colour: "#CCA7D0", counter_bg_colour: "#515B8D60" },
    stats: { header_colour: "#E97BC1", stats_subheader_colour: "#4394C4", stats_text_colour: "#ACB5BA", col2_date_colour: "#4394C4", col2_hours_colour: "#E97BC1", cal_weekday_colour: "#E97BC1", cal_number_colour: "#C45281", cal_number_end_colour: "#C45281", cal_streak_middle_colour: "#AF96FF40", cal_streak_end_colour: "#DEBCE9" },
    weekly_stats: { title_colour: "#DF7DB3", top_hours_colour: "#E2E2E2", top_weekday_colour: "#ADB6BB", top_date_colour: "#ADB6BB", top_this_colour: "#DF7DB3", top_last_colour: "#7B98CE80", btm_weekday_colour: "#E2E2E2", btm_day_colour: "#846967", btm_this_colour: "#8283BF", btm_last_colour: "#DF879080", btm_bar_horiz_colour: "#B2B8D866", this_week_colour: "#DF7DB3", last_week_colour: "#7B98CE80", footer_colour: "#49679A" },
    monthly_stats: { title_colour: "#DF7DB3", top_hours_colour: "#E2E2E2", top_hours_bg_colour: "#5359A7", top_date_colour: "#ADB6BB", top_line_colour: "#8FD4D726", top_this_colour: "#DF7DB3", top_this_hours_colour: "#DF7DB3", top_last_colour: "#7B98CE73", top_last_hours_colour: "#7B98CE73", this_month_colour: "#5E5C75", last_month_colour: "#5E5C75", weekday_background_colour: "#5359A7", weekday_colour: "#E2E2E2", month_background_colour: "#5359A7", month_colour: "#E2E2E2", stats_key_colour: "#ADB6BB", stats_value_colour: "#ADB6BB", footer_colour: "#49679A" },
    weekly_goals: { title_colour: "#E97BC1", mini_profile_name_colour: "#1E9AC4", mini_profile_discrim_colour: "#2276A0", mini_profile_badge_colour: "#E97BC1", mini_profile_badge_text_colour: "#152A4A", progress_bg_colour: "#DF7DB340", progress_colour: "#DF7DB3", attendance_colour: "#846967", attendance_rate_colour: "#DA847E", task_count_colour: "#DA847E", task_done_colour: "#846967", studied_text_colour: "#846967", task_goal_colour: "#846967", studied_hour_colour: "#DA847E", task_goal_number_colour: "#846967", task_done_number_colour: "#78A7D9", task_undone_number_colour: "#78A7D9", task_done_text_colour: "#4C426A", task_undone_text_colour: "#A6B4BC", footer_colour: "#49679A" },
    monthly_goals: { title_colour: "#E97BC1", mini_profile_name_colour: "#1E9AC4", mini_profile_discrim_colour: "#2276A0", mini_profile_badge_colour: "#E97BC1", mini_profile_badge_text_colour: "#152A4A", progress_bg_colour: "#DF7DB340", progress_colour: "#DF7DB3", attendance_colour: "#846967", attendance_rate_colour: "#DA847E", task_count_colour: "#DA847E", task_done_colour: "#846967", studied_text_colour: "#846967", task_goal_colour: "#846967", studied_hour_colour: "#DA847E", task_goal_number_colour: "#846967", task_done_number_colour: "#78A7D9", task_undone_number_colour: "#78A7D9", task_done_text_colour: "#4C426A", task_undone_text_colour: "#A6B4BC", footer_colour: "#49679A" },
    leaderboard: { header_text_colour: "#DF7DB3", subheader_name_colour: "#B4BBC5", subheader_value_colour: "#B4BBC5", top_position_colour: "#55B9E1", top_name_colour: "#FFFFFF", top_hours_colour: "#C9C0C0", entry_position_colour: "#55B9E1", entry_position_highlight_colour: "#FFFFFF", entry_name_colour: "#FFFFFF", entry_hours_colour: "#FFFFFF", entry_bg_colour: "#142A4A", entry_bg_highlight_colour: "#7A8FC8" },
  },
  cotton_candy: {
    profile: { header_colour_1: "#FFFFFF", header_colour_2: "#F8E1E7", subheader_colour: "#FFFFFF", badge_text_colour: "#7191E2", badge_blob_colour: "#F9F9F9", rank_name_colour: "#FFFFFF", rank_hours_colour: "#704E8D", next_rank_colour: "#704E8D", bar_full_colour: "#FFE894", bar_empty_colour: "#FFE8944D", counter_colour: "#DEB2B240", counter_bg_colour: "#515B8D60" },
    stats: { header_colour: "#FFFFFF", stats_subheader_colour: "#FFFFFF", stats_text_colour: "#FFFFFF", col2_date_colour: "#CED9F5", col2_hours_colour: "#FFFFFF", cal_weekday_colour: "#FFFFFF", cal_number_colour: "#CED9F5", cal_number_end_colour: "#FFFFFF", cal_streak_middle_colour: "#DEB2B240", cal_streak_end_colour: "#FF8B8B" },
    weekly_stats: { title_colour: "#FFFFFF", top_hours_colour: "#FFFFFF", top_weekday_colour: "#E1E3F2", top_date_colour: "#E1E3F2", top_this_colour: "#D7DABB", top_last_colour: "#E8EAE880", btm_weekday_colour: "#FFFFFF", btm_day_colour: "#FFFFFF", btm_this_colour: "#8B9ACD", btm_last_colour: "#3D486F80", btm_bar_horiz_colour: "#546CB380", this_week_colour: "#D1D3E4", last_week_colour: "#D1D3E4", footer_colour: "#DCDCDC" },
    monthly_stats: { title_colour: "#FFFFFF", top_hours_colour: "#FFFFFF", top_hours_bg_colour: "#546CB3", top_date_colour: "#D1D3E4", top_line_colour: "#FFFFFF60", top_this_colour: "#D7DABB", top_this_hours_colour: "#D7DABB", top_last_colour: "#82869F73", top_last_hours_colour: "#5D659A", this_month_colour: "#D1D3E4", last_month_colour: "#D1D3E4", weekday_background_colour: "#546CB380", weekday_colour: "#FFFFFF", month_background_colour: "#546CB380", month_colour: "#FFFFFF", stats_key_colour: "#494556", stats_value_colour: "#494556", footer_colour: "#DCDCDC" },
    weekly_goals: { title_colour: "#FFFFFF", mini_profile_name_colour: "#FFFFFF", mini_profile_discrim_colour: "#F8E1E7", mini_profile_badge_colour: "#F9F9F9", mini_profile_badge_text_colour: "#7191E2", progress_bg_colour: "#FEE79340", progress_colour: "#FEE793", attendance_colour: "#FFFFFF", attendance_rate_colour: "#ECEAD0", task_count_colour: "#ECEAD0", task_done_colour: "#FFFFFF", studied_text_colour: "#FFFFFF", task_goal_colour: "#FFFFFF", studied_hour_colour: "#ECEAD0", task_goal_number_colour: "#FFFFFF", task_done_number_colour: "#FFFFFF", task_undone_number_colour: "#FFFFFF", task_done_text_colour: "#9A9ECF", task_undone_text_colour: "#FFFFFF", footer_colour: "#DCDCDC" },
    monthly_goals: { title_colour: "#FFFFFF", mini_profile_name_colour: "#FFFFFF", mini_profile_discrim_colour: "#F8E1E7", mini_profile_badge_colour: "#F9F9F9", mini_profile_badge_text_colour: "#7191E2", progress_bg_colour: "#FEE79340", progress_colour: "#FEE793", attendance_colour: "#FFFFFF", attendance_rate_colour: "#ECEAD0", task_count_colour: "#ECEAD0", task_done_colour: "#FFFFFF", studied_text_colour: "#FFFFFF", task_goal_colour: "#FFFFFF", studied_hour_colour: "#ECEAD0", task_goal_number_colour: "#FFFFFF", task_done_number_colour: "#FFFFFF", task_undone_number_colour: "#FFFFFF", task_done_text_colour: "#9A9ECF", task_undone_text_colour: "#FFFFFF", footer_colour: "#DCDCDC" },
    leaderboard: { header_text_colour: "#FFFFFF", subheader_name_colour: "#474D5E", subheader_value_colour: "#474D5E", top_position_colour: "#FFFFFF", top_name_colour: "#FFFFFF", top_hours_colour: "#474D5E", entry_position_colour: "#FFFFFF", entry_position_highlight_colour: "#FFFFFF", entry_name_colour: "#FFFFFF", entry_hours_colour: "#FFFFFF", entry_bg_colour: "#DEB3B2", entry_bg_highlight_colour: "#96AFDB" },
  },
  blue_bayoux: {
    profile: { header_colour_1: "#B79AE2", header_colour_2: "#867F93", subheader_colour: "#FFFFFF", badge_text_colour: "#6671D3", badge_blob_colour: "#FFFFFF", rank_name_colour: "#FFFFFF", rank_hours_colour: "#D0D0D0", next_rank_colour: "#D0D0D0", bar_full_colour: "#B79AE2", bar_empty_colour: "#B79AE24D", counter_colour: "#B79AE24D", counter_bg_colour: "#515B8D60" },
    stats: { header_colour: "#FFFFFF", stats_subheader_colour: "#869EBD", stats_text_colour: "#DEDEDE", col2_date_colour: "#869EBD", col2_hours_colour: "#FFFFFF", cal_weekday_colour: "#FFFFFF", cal_number_colour: "#D9CAC9", cal_number_end_colour: "#FFFFFF", cal_streak_middle_colour: "#70CDEB40", cal_streak_end_colour: "#4E89F4" },
    weekly_stats: { title_colour: "#FFFFFF", top_hours_colour: "#E2E2E2", top_weekday_colour: "#DFDFDE", top_date_colour: "#DFDFDE", top_this_colour: "#AF8EC2", top_last_colour: "#AF8EC280", btm_weekday_colour: "#E2E2E2", btm_day_colour: "#E2E2E2", btm_this_colour: "#AF8EC2", btm_last_colour: "#AF8EC280", btm_bar_horiz_colour: "#FFFFFF80", this_week_colour: "#AF8EC2", last_week_colour: "#AF8EC280", footer_colour: "#5B5F80" },
    monthly_stats: { title_colour: "#FFFFFF", top_hours_colour: "#E2E2E2", top_hours_bg_colour: "#6762AC", top_date_colour: "#DFDFDE", top_line_colour: "#8FD4D727", top_this_colour: "#AF8EC2", top_this_hours_colour: "#FFF3F0", top_last_colour: "#6F7BA073", top_last_hours_colour: "#FFF3F0", this_month_colour: "#D1D3E4", last_month_colour: "#D1D3E4", weekday_background_colour: "#6762AC", weekday_colour: "#E2E2E2", month_background_colour: "#6762AC", month_colour: "#E2E2E2", stats_key_colour: "#DFDFDE", stats_value_colour: "#DFDFDE", footer_colour: "#5B5F80" },
    weekly_goals: { title_colour: "#FFFFFF", mini_profile_name_colour: "#B79AE2", mini_profile_discrim_colour: "#867F93", mini_profile_badge_colour: "#FFFFFF", mini_profile_badge_text_colour: "#6671D3", progress_bg_colour: "#BFD7F040", progress_colour: "#BFD7F0", attendance_colour: "#8094B9", attendance_rate_colour: "#C4E9F7", task_count_colour: "#C4E9F7", task_done_colour: "#8094B9", studied_text_colour: "#8094B9", task_goal_colour: "#8094B9", studied_hour_colour: "#C4E9F7", task_goal_number_colour: "#8094B9", task_done_number_colour: "#DCD3E9", task_undone_number_colour: "#CCCCCC", task_done_text_colour: "#989898", task_undone_text_colour: "#CCCCCC", footer_colour: "#5B5F80" },
    monthly_goals: { title_colour: "#FFFFFF", mini_profile_name_colour: "#B79AE2", mini_profile_discrim_colour: "#867F93", mini_profile_badge_colour: "#FFFFFF", mini_profile_badge_text_colour: "#6671D3", progress_bg_colour: "#BFD7F040", progress_colour: "#BFD7F0", attendance_colour: "#8094B9", attendance_rate_colour: "#C4E9F7", task_count_colour: "#C4E9F7", task_done_colour: "#8094B9", studied_text_colour: "#8094B9", task_goal_colour: "#8094B9", studied_hour_colour: "#C4E9F7", task_goal_number_colour: "#8094B9", task_done_number_colour: "#DCD3E9", task_undone_number_colour: "#CCCCCC", task_done_text_colour: "#989898", task_undone_text_colour: "#CCCCCC", footer_colour: "#5B5F80" },
    leaderboard: { header_text_colour: "#FFFFFF", subheader_name_colour: "#A2AEBE", subheader_value_colour: "#A2AEBE", top_position_colour: "#D5BEDC", top_name_colour: "#FFFFFF", top_hours_colour: "#C9C0C0", entry_position_colour: "#FFFFFF", entry_position_highlight_colour: "#FFFFFF", entry_name_colour: "#FFFFFF", entry_hours_colour: "#FFFFFF", entry_bg_colour: "#4765AF", entry_bg_highlight_colour: "#8A68AD73" },
  },
  bubblegum: {
    profile: { header_colour_1: "#FFF2D4", header_colour_2: "#FFF2D4", subheader_colour: "#FFFFFF", badge_text_colour: "#FF3589", badge_blob_colour: "#FFF2D4", rank_name_colour: "#FFFFFF", rank_hours_colour: "#DBDBDB", next_rank_colour: "#DBDBDB", bar_full_colour: "#99D3EE", bar_empty_colour: "#99D3EE4D", counter_colour: "#99D3EE4D", counter_bg_colour: "#515B8D60" },
    stats: { header_colour: "#FFFFFF", stats_subheader_colour: "#869EBD", stats_text_colour: "#FFFFFF", col2_date_colour: "#FFFFFF", col2_hours_colour: "#99D3EE", cal_weekday_colour: "#FFFFFF", cal_number_colour: "#E4CCD5", cal_number_end_colour: "#FFFFFF", cal_streak_middle_colour: "#EEB4F640", cal_streak_end_colour: "#FF90E1" },
    weekly_stats: { title_colour: "#FFFFFF", top_hours_colour: "#345AA9", top_weekday_colour: "#FFEDD5", top_date_colour: "#FFEDD5", top_this_colour: "#DCBCDA", top_last_colour: "#D1A6CD8C", btm_weekday_colour: "#FFEDD5", btm_day_colour: "#DCDBDB", btm_this_colour: "#DCBCDA", btm_last_colour: "#D1A6CD8C", btm_bar_horiz_colour: "#FFFFFF80", this_week_colour: "#DCDBDB", last_week_colour: "#DCDBDB", footer_colour: "#DCDCDC" },
    monthly_stats: { title_colour: "#FFFFFF", top_hours_colour: "#345AA9", top_hours_bg_colour: "#FFFAF1", top_date_colour: "#FFEDD5", top_line_colour: "#8FD4D726", top_this_colour: "#DCBCDA", top_this_hours_colour: "#DCBCDA", top_last_colour: "#D1A6CD73", top_last_hours_colour: "#FDF8F8", this_month_colour: "#DCDBDB", last_month_colour: "#DCDBDB", weekday_background_colour: "#FFFAF1", weekday_colour: "#345AA9", month_background_colour: "#FFFAF1", month_colour: "#345AA9", stats_key_colour: "#DCDBDB", stats_value_colour: "#DCDBDB", footer_colour: "#DCA9A3" },
    weekly_goals: { title_colour: "#FFFFFF", mini_profile_name_colour: "#FFF2D4", mini_profile_discrim_colour: "#FFF2D4", mini_profile_badge_colour: "#FFF2D4", mini_profile_badge_text_colour: "#FF3589", progress_bg_colour: "#DCBCDA40", progress_colour: "#F2BFCE", attendance_colour: "#DCDBDB", attendance_rate_colour: "#EAB1D1", task_count_colour: "#EAB1D1", task_done_colour: "#DCDBDB", studied_text_colour: "#DCDBDB", task_goal_colour: "#DCDBDB", studied_hour_colour: "#EAB1D1", task_goal_number_colour: "#EAB1D1", task_done_number_colour: "#FFFFFF", task_undone_number_colour: "#FFFFFF", task_done_text_colour: "#889DA7", task_undone_text_colour: "#FBF7F3", footer_colour: "#DCA9A3" },
    monthly_goals: { title_colour: "#FFFFFF", mini_profile_name_colour: "#FFF2D4", mini_profile_discrim_colour: "#FFF2D4", mini_profile_badge_colour: "#FFF2D4", mini_profile_badge_text_colour: "#FF3589", progress_bg_colour: "#DCBCDA40", progress_colour: "#F2BFCE", attendance_colour: "#DCDBDB", attendance_rate_colour: "#EAB1D1", task_count_colour: "#EAB1D1", task_done_colour: "#DCDBDB", studied_text_colour: "#DCDBDB", task_goal_colour: "#DCDBDB", studied_hour_colour: "#EAB1D1", task_goal_number_colour: "#EAB1D1", task_done_number_colour: "#FFFFFF", task_undone_number_colour: "#FFFFFF", task_done_text_colour: "#889DA7", task_undone_text_colour: "#FBF7F3", footer_colour: "#DCA9A3" },
    leaderboard: { header_text_colour: "#FFFFFF", subheader_name_colour: "#A2AEBE", subheader_value_colour: "#A2AEBE", top_position_colour: "#D5BEDC", top_name_colour: "#FFFFFF", top_hours_colour: "#C9C0C0", entry_position_colour: "#FFFFFF", entry_position_highlight_colour: "#FFFFFF", entry_name_colour: "#FFFFFF", entry_hours_colour: "#FFFFFF", entry_bg_colour: "#8A68AD73", entry_bg_highlight_colour: "#4765AF" },
  },
}

export function getDefaultColor(skinName: string, cardType: string, propertyKey: string): string {
  return SKIN_DEFAULTS[skinName]?.[cardType]?.[propertyKey]
    ?? SKIN_DEFAULTS.original?.[cardType]?.[propertyKey]
    ?? "#808080"
}
