// ============================================================
// AI-GENERATED FILE
// Created: 2026-04-30
// Updated: 2026-04-30 (editorial redesign)
// Purpose: Embeddable widget for a public server listing. External
//          sites paste an <iframe src="https://lionbot.org/embed/server/{slug}">
//          snippet (generated by the dashboard editor) and it
//          renders a compact, theme-aware card.
//
//          v2 (editorial redesign): the widget mirrors the editorial
//          visual language of the public profile -- serif name,
//          italic tagline, hairline rules, no rounded card chrome.
//          Each theme keeps its own surface, font pair, and accent
//          treatment so the embed *previews* the page it links to.
//
//          ISR with a 5-minute revalidation so admin edits propagate
//          to every external embed without a manual cache bust.
//          X-Frame-Options=ALLOWALL is set in next.config for this
//          path so cross-site iframing actually works.
// ============================================================
import Head from "next/head"
import { GetStaticPaths, GetStaticProps } from "next"
import Link from "next/link"
import EmbedLayout from "@/components/embed/EmbedLayout"
import { prisma } from "@/utils/prisma"
import {
  resolveTheme,
  ListingTheme,
} from "@/constants/ServerListingData"
import { SERVERS_DIRECTORY_ENABLED } from "@/constants/FeatureFlags"
import { withAlpha } from "@/components/listing/EditorialThemeProvider"
import { getListingPremiumStatus } from "@/utils/listingHelpers"

interface EmbedListing {
  slug: string
  display_name: string
  tagline: string | null
  category: string
  cover_image_url: string | null
  guild_icon_url: string | null
  theme_preset: string
  accent_color: string | null
  is_study_server: boolean
}

interface EmbedProps {
  listing: EmbedListing | null
}

export const getStaticPaths: GetStaticPaths = async () => ({
  paths: [],
  fallback: "blocking",
})

export const getStaticProps: GetStaticProps<EmbedProps> = async (ctx) => {
  // Feature gate -- see constants/FeatureFlags.ts. Hide the embed
  // widget so external sites can't iframe a half-built feature.
  if (!SERVERS_DIRECTORY_ENABLED) {
    return { notFound: true, revalidate: 300 }
  }

  const slugParam = ctx.params?.slug
  const slug = Array.isArray(slugParam) ? slugParam[0] : slugParam
  if (!slug) {
    return { notFound: true }
  }

  const row = await prisma.server_listings.findFirst({
    where: { slug, status: "APPROVED" },
    select: {
      guildid: true,
      slug: true,
      display_name: true,
      tagline: true,
      category: true,
      cover_image_url: true,
      guild_icon_url: true,
      theme_preset: true,
      accent_color: true,
      is_study_server: true,
    },
  })

  if (!row) {
    return { notFound: true, revalidate: 60 }
  }

  const premium = await getListingPremiumStatus(row.guildid)
  if (!premium.isPremium && !premium.inGracePeriod) {
    return { notFound: true, revalidate: 300 }
  }

  return {
    props: {
      listing: {
        slug: row.slug,
        display_name: row.display_name,
        tagline: row.tagline,
        category: row.category,
        cover_image_url: row.cover_image_url,
        guild_icon_url: row.guild_icon_url,
        theme_preset: row.theme_preset,
        accent_color: row.accent_color,
        is_study_server: row.is_study_server,
      },
    },
    revalidate: 300,
  }
}

export default function ServerEmbedPage({ listing }: EmbedProps) {
  if (!listing) {
    return (
      <EmbedLayout title="LionBot">
        <div style={{ padding: 16, fontSize: 13, color: "#94a3b8", fontFamily: "Inter, sans-serif" }}>
          This server listing is no longer available.
        </div>
      </EmbedLayout>
    )
  }

  const theme = resolveTheme(listing.theme_preset)
  const accent = listing.accent_color || theme.defaultAccent

  const fontHrefs = theme.googleFonts.map(
    (slug) => `https://fonts.googleapis.com/css2?family=${slug}&display=swap`,
  )

  return (
    <EmbedLayout title={`${listing.display_name} on LionBot`}>
      <Head>
        {fontHrefs.map((href) => (
          <link key={href} rel="stylesheet" href={href} />
        ))}
      </Head>
      <article
        style={{
          width: "100%",
          maxWidth: 380,
          background: theme.bodyBg,
          color: theme.bodyText,
          fontFamily: theme.bodyFont,
          // Match the magazine aesthetic: square / softly rounded
          // depending on theme, no aggressive card chrome.
          borderRadius: theme.id === "wired" || theme.id === "frieze" ? 0 : 4,
          overflow: "hidden",
          // Hairline border instead of a deep shadow so the widget
          // sits cleanly on light AND dark host pages.
          border: `1px solid ${theme.ruleColor}`,
          boxShadow: "0 6px 24px rgba(0,0,0,0.10)",
        }}
      >
        {/* Cover band -- short, themed treatment */}
        <CoverBand theme={theme} accent={accent} url={listing.cover_image_url} />

        <div style={{ padding: "18px 20px 16px" }}>
          {/* Kicker */}
          <KickerRow
            theme={theme}
            accent={accent}
            category={listing.category}
            isStudy={listing.is_study_server}
          />

          {/* Serif name */}
          <h2
            style={{
              margin: "10px 0 0",
              fontFamily: theme.displayFont,
              fontSize: theme.id === "frieze" ? 26 : theme.id === "wired" ? 22 : 24,
              fontWeight: theme.id === "wired" ? 900 : 700,
              lineHeight: 1.05,
              letterSpacing: "-0.02em",
              textTransform: theme.id === "wired" ? "uppercase" : "none",
              color: theme.bodyText,
            }}
          >
            {listing.display_name}
          </h2>

          {/* Italic deck */}
          {listing.tagline ? (
            <p
              style={{
                margin: "8px 0 0",
                fontFamily: theme.italicDeck ? theme.displayFont : theme.bodyFont,
                fontStyle: theme.italicDeck ? "italic" : "normal",
                fontSize: 13,
                lineHeight: 1.55,
                color: theme.mutedText,
                display: "-webkit-box",
                WebkitLineClamp: 2,
                WebkitBoxOrient: "vertical",
                overflow: "hidden",
              }}
            >
              {listing.tagline}
            </p>
          ) : null}

          {/* Hairline rule (skip on Frieze which uses none) */}
          {theme.ruleStyle !== "none" && (
            <div
              style={{
                marginTop: 14,
                borderTop:
                  theme.ruleStyle === "thick"
                    ? `2px solid ${accent}`
                    : theme.ruleStyle === "double"
                    ? `3px double ${theme.ruleColor}`
                    : `1px solid ${theme.ruleColor}`,
              }}
            />
          )}

          {/* CTA row */}
          <div style={{ display: "flex", alignItems: "center", gap: 10, marginTop: 14 }}>
            <a
              href={`/api/servers/${encodeURIComponent(listing.slug)}/join?ref=embed`}
              target="_top"
              rel="noopener"
              style={{
                background: theme.id === "frieze" ? theme.bodyText : accent,
                color: theme.id === "frieze" ? theme.bodyBg : (theme.id === "wired" ? "#0a0a0c" : "#ffffff"),
                fontFamily: theme.bodyFont,
                fontSize: 12.5,
                fontWeight: 600,
                letterSpacing: theme.id === "wired" ? 0.6 : 0.2,
                textTransform: theme.id === "wired" ? "uppercase" : "none",
                padding: "9px 14px",
                borderRadius: theme.id === "wired" || theme.id === "frieze" ? 0 : 999,
                textDecoration: "none",
              }}
            >
              {theme.id === "wired" ? "Open invite" : "Join the community"}
            </a>
            <Link href={`/servers/${listing.slug}`} passHref>
              <a
                target="_top"
                style={{
                  fontFamily: theme.bodyFont,
                  fontSize: 12,
                  fontWeight: 500,
                  color: theme.mutedText,
                  textDecoration: "underline",
                  textUnderlineOffset: 3,
                  textDecorationColor: theme.ruleColor,
                }}
              >
                Read listing →
              </a>
            </Link>
          </div>

          {/* Colophon */}
          <div
            style={{
              marginTop: 14,
              paddingTop: 10,
              borderTop: `1px solid ${theme.ruleColor}`,
              fontFamily: theme.id === "frieze" ? "Menlo, monospace" : theme.bodyFont,
              fontSize: 10,
              letterSpacing: theme.id === "frieze" ? 1.5 : 1.2,
              textTransform: "uppercase",
              color: theme.mutedText,
              display: "flex",
              justifyContent: "space-between",
              alignItems: "center",
            }}
          >
            <span>lionbot.org/servers/{listing.slug}</span>
            <a
              href="https://lionbot.org/servers"
              target="_top"
              rel="noopener"
              style={{ color: theme.bodyText, textDecoration: "none", fontWeight: 600 }}
            >
              LionBot
            </a>
          </div>
        </div>
      </article>
    </EmbedLayout>
  )
}

// ── Sub-components ────────────────────────────────────────────

function CoverBand({
  theme,
  accent,
  url,
}: {
  theme: ListingTheme
  accent: string
  url: string | null
}) {
  // The widget's cover band is visually short (96px) but we still
  // honour the theme's blend recipe. Atlantic = soft fade, Wired =
  // accent-tinted darkening, Kinfolk = monochrome, Vogue = wash,
  // Frieze = minimal vignette.
  if (!url) {
    return (
      <div
        style={{
          height: 64,
          background:
            theme.id === "wired"
              ? `linear-gradient(135deg, ${withAlpha(accent, 0.55)}, #0a0a0c)`
              : `linear-gradient(135deg, ${withAlpha(accent, 0.16)}, ${theme.bodyBg})`,
        }}
      />
    )
  }

  const safeUrl = url.replace(/'/g, "%27").replace(/"/g, "%22")
  let bg: string
  let filter: string | undefined
  switch (theme.coverBlend) {
    case "duotone":
      bg = `linear-gradient(180deg, rgba(10,10,12,0.20), rgba(10,10,12,0.85)), linear-gradient(135deg, ${withAlpha(accent, 0.55)}, transparent), url('${safeUrl}') center/cover`
      filter = "contrast(1.05)"
      break
    case "monochrome":
      bg = `linear-gradient(180deg, transparent, ${withAlpha(theme.bodyBg, 0.65)}), url('${safeUrl}') center/cover`
      filter = "grayscale(0.95) contrast(1.02)"
      break
    case "wash":
      bg = `linear-gradient(180deg, transparent, ${withAlpha(theme.bodyBg, 0.7)}), linear-gradient(135deg, ${withAlpha(accent, 0.18)}, transparent), url('${safeUrl}') center/cover`
      break
    case "spare":
      bg = `linear-gradient(180deg, transparent, ${withAlpha(theme.bodyBg, 0.85)}), url('${safeUrl}') center/cover`
      break
    case "paper":
    default:
      bg = `linear-gradient(180deg, transparent, ${withAlpha(theme.bodyBg, 0.55)}, ${theme.bodyBg}), url('${safeUrl}') center/cover`
      break
  }

  return (
    <div
      style={{
        height: 96,
        background: bg,
        filter,
      }}
    />
  )
}

function KickerRow({
  theme,
  accent,
  category,
  isStudy,
}: {
  theme: ListingTheme
  accent: string
  category: string
  isStudy: boolean
}) {
  const items: string[] = ["FEATURED"]
  items.push(category.toUpperCase())
  if (isStudy) items.push("STUDY")

  const baseStyle: React.CSSProperties = {
    fontFamily: theme.id === "frieze" ? "Menlo, monospace" : theme.bodyFont,
    fontSize: 9,
    fontWeight: 600,
    letterSpacing: theme.id === "frieze" ? 2.2 : 1.8,
    textTransform: "uppercase",
    color: theme.mutedText,
    display: "inline-flex",
    alignItems: "center",
    gap: 8,
  }

  if (theme.id === "wired") {
    return (
      <div style={baseStyle}>
        <span style={{ display: "inline-block", width: 22, height: 1.5, background: accent }} aria-hidden="true" />
        <span style={{ color: accent }}>{items[0]}</span>
        <span aria-hidden="true">·</span>
        <span>{items.slice(1).join("  ·  ")}</span>
      </div>
    )
  }

  return <div style={baseStyle}>{items.join("   ·   ")}</div>
}
