// ============================================================
// AI-GENERATED FILE
// Created: 2026-04-30
// Purpose: Embeddable widget for a public server listing. External
//          sites paste an <iframe src="https://lionbot.org/embed/server/{slug}">
//          snippet (generated by the dashboard editor) and it
//          renders a compact, theme-aware card with the server's
//          cover, name, tagline, key tag, and a "Join Discord"
//          button that hits our tracked redirect.
//
//          We ISR with a 5-minute revalidation so changes the
//          admin makes (cover, accent, theme) propagate quickly
//          without us having to invalidate every external embed.
//
//          The route renders inside EmbedLayout (transparent
//          background, no nav) so it sits cleanly inside any
//          host page. We also set X-Frame-Options=ALLOWALL via
//          next.config so cross-site iframing actually works
//          (default is SAMEORIGIN for the rest of the site).
// ============================================================
import { GetStaticPaths, GetStaticProps } from "next"
import Link from "next/link"
import EmbedLayout from "@/components/embed/EmbedLayout"
import { prisma } from "@/utils/prisma"
import { LISTING_THEMES } from "@/constants/ServerListingData"
import { getListingPremiumStatus } from "@/utils/listingHelpers"

interface EmbedListing {
  slug: string
  display_name: string
  tagline: string | null
  category: string
  cover_image_url: string | null
  guild_icon_url: string | null
  theme_preset: string
  accent_color: string | null
  is_study_server: boolean
  member_count: number | null
}

interface EmbedProps {
  listing: EmbedListing | null
}

export const getStaticPaths: GetStaticPaths = async () => ({
  paths: [],
  fallback: "blocking",
})

export const getStaticProps: GetStaticProps<EmbedProps> = async (ctx) => {
  const slugParam = ctx.params?.slug
  const slug = Array.isArray(slugParam) ? slugParam[0] : slugParam
  if (!slug) {
    return { notFound: true }
  }

  const row = await prisma.server_listings.findFirst({
    where: { slug, status: "APPROVED" },
    select: {
      guildid: true,
      slug: true,
      display_name: true,
      tagline: true,
      category: true,
      cover_image_url: true,
      guild_icon_url: true,
      theme_preset: true,
      accent_color: true,
      is_study_server: true,
    },
  })

  if (!row) {
    return { notFound: true, revalidate: 60 }
  }

  const premium = await getListingPremiumStatus(row.guildid)
  if (!premium.isPremium && !premium.inGracePeriod) {
    return { notFound: true, revalidate: 300 }
  }

  return {
    props: {
      listing: {
        slug: row.slug,
        display_name: row.display_name,
        tagline: row.tagline,
        category: row.category,
        cover_image_url: row.cover_image_url,
        guild_icon_url: row.guild_icon_url,
        theme_preset: row.theme_preset,
        accent_color: row.accent_color,
        is_study_server: row.is_study_server,
        member_count: null,
      },
    },
    revalidate: 300,
  }
}

export default function ServerEmbedPage({ listing }: EmbedProps) {
  if (!listing) {
    return (
      <EmbedLayout title="LionBot">
        <div style={{ padding: 16, fontSize: 13, color: "#94a3b8" }}>
          This server listing is no longer available.
        </div>
      </EmbedLayout>
    )
  }

  const theme =
    LISTING_THEMES.find((t) => t.id === listing.theme_preset) ?? LISTING_THEMES[0]
  const accent = listing.accent_color || theme.defaultAccent

  return (
    <EmbedLayout title={`${listing.display_name} on LionBot`}>
      <div
        style={{
          width: "100%",
          maxWidth: 360,
          background: theme.cardSurface,
          color: theme.textTone === "light" ? "#f8fafc" : "#0f172a",
          borderRadius: 14,
          overflow: "hidden",
          boxShadow: "0 18px 40px rgba(0,0,0,0.35)",
          fontFamily: "Inter, system-ui, sans-serif",
        }}
      >
        <div
          style={{
            position: "relative",
            height: 96,
            background: listing.cover_image_url
              ? `url(${listing.cover_image_url}) center/cover`
              : `linear-gradient(135deg, ${accent}88, ${accent}33)`,
          }}
        >
          <div
            style={{
              position: "absolute",
              inset: 0,
              background:
                "linear-gradient(180deg, rgba(0,0,0,0.05) 0%, rgba(0,0,0,0.55) 100%)",
            }}
          />
          {listing.guild_icon_url ? (
            <img
              src={listing.guild_icon_url}
              alt=""
              width={56}
              height={56}
              style={{
                position: "absolute",
                bottom: -22,
                left: 14,
                borderRadius: 14,
                border: "3px solid " + theme.cardSurface,
                background: "#1f2937",
                objectFit: "cover",
              }}
            />
          ) : (
            <div
              style={{
                position: "absolute",
                bottom: -22,
                left: 14,
                width: 56,
                height: 56,
                borderRadius: 14,
                border: "3px solid " + theme.cardSurface,
                background: accent,
                color: "#0b1020",
                display: "flex",
                alignItems: "center",
                justifyContent: "center",
                fontWeight: 800,
              }}
            >
              {listing.display_name.charAt(0).toUpperCase()}
            </div>
          )}
        </div>

        <div style={{ padding: "30px 16px 16px 16px" }}>
          <div style={{ display: "flex", alignItems: "center", gap: 6, flexWrap: "wrap" }}>
            <h2 style={{ margin: 0, fontSize: 16, fontWeight: 700 }}>
              {listing.display_name}
            </h2>
            {listing.is_study_server && (
              <span
                style={{
                  fontSize: 10,
                  fontWeight: 600,
                  letterSpacing: 0.6,
                  textTransform: "uppercase",
                  background: accent + "22",
                  color: accent,
                  borderRadius: 6,
                  padding: "2px 6px",
                }}
              >
                Study
              </span>
            )}
          </div>
          {listing.tagline ? (
            <p
              style={{
                margin: "6px 0 0 0",
                fontSize: 12.5,
                lineHeight: 1.5,
                color:
                  theme.textTone === "light"
                    ? "rgba(255,255,255,0.78)"
                    : "rgba(15,23,42,0.78)",
              }}
            >
              {listing.tagline}
            </p>
          ) : null}

          <div style={{ display: "flex", gap: 8, marginTop: 12 }}>
            <a
              href={`/api/servers/${encodeURIComponent(listing.slug)}/join?ref=embed`}
              target="_top"
              rel="noopener"
              style={{
                flex: 1,
                display: "inline-flex",
                alignItems: "center",
                justifyContent: "center",
                background: accent,
                color: "#0b1020",
                borderRadius: 8,
                padding: "8px 12px",
                fontSize: 12.5,
                fontWeight: 700,
                textDecoration: "none",
              }}
            >
              Join Discord
            </a>
            <Link href={`/servers/${listing.slug}`}>
              <a
                target="_top"
                style={{
                  display: "inline-flex",
                  alignItems: "center",
                  justifyContent: "center",
                  border: "1px solid rgba(255,255,255,0.18)",
                  color:
                    theme.textTone === "light"
                      ? "rgba(255,255,255,0.85)"
                      : "rgba(15,23,42,0.78)",
                  borderRadius: 8,
                  padding: "8px 12px",
                  fontSize: 12,
                  fontWeight: 600,
                  textDecoration: "none",
                }}
              >
                Profile
              </a>
            </Link>
          </div>

          <div
            style={{
              marginTop: 10,
              fontSize: 10.5,
              color:
                theme.textTone === "light"
                  ? "rgba(255,255,255,0.5)"
                  : "rgba(15,23,42,0.5)",
              display: "flex",
              alignItems: "center",
              gap: 4,
            }}
          >
            <span>Powered by</span>
            <a
              href="https://lionbot.org/servers"
              target="_top"
              rel="noopener"
              style={{
                color:
                  theme.textTone === "light"
                    ? "rgba(255,255,255,0.7)"
                    : "rgba(15,23,42,0.7)",
                textDecoration: "underline",
              }}
            >
              LionBot
            </a>
          </div>
        </div>
      </div>
    </EmbedLayout>
  )
}
