// ============================================================
// AI-GENERATED FILE
// Created: 2026-03-22
// Purpose: Static search registry for dashboard command palette
//          and sidebar search. Maps all pages, settings sections,
//          and feature-specific settings to routes and keywords.
// ============================================================

export type SearchCategory = "page" | "setting" | "feature"

export interface SearchItem {
  id: string
  title: string
  description: string
  category: SearchCategory
  /** The parent page name shown as breadcrumb (e.g. "Settings") */
  page: string
  /** Relative route from /dashboard/servers/[id] */
  route: string
  /** Section anchor to scroll to (settings page deep-link) */
  section?: string
  keywords: string[]
  /** Lucide icon name for display */
  iconName: string
  premium?: boolean
  /** "admin" = admin only, "mod" = mod+admin, undefined = everyone */
  requiredLevel?: "admin" | "mod"
}

const PAGE_ITEMS: SearchItem[] = [
  {
    id: "page-dashboard",
    title: "Dashboard",
    description: "Server overview and quick stats",
    category: "page",
    page: "Overview",
    route: "",
    keywords: ["overview", "home", "dashboard", "stats", "summary"],
    iconName: "BarChart3",
  },
  {
    id: "page-members",
    title: "Members",
    description: "View and manage server members",
    category: "page",
    page: "Management",
    route: "/members",
    keywords: ["members", "users", "people", "list"],
    iconName: "Users",
    requiredLevel: "mod",
  },
  {
    id: "page-moderation",
    title: "Moderation",
    description: "Moderation records and actions",
    category: "page",
    page: "Management",
    route: "/moderation",
    keywords: ["moderation", "ban", "warn", "restrict", "punish"],
    iconName: "Shield",
    requiredLevel: "mod",
  },
  {
    id: "page-economy",
    title: "Economy",
    description: "Coin stats, transactions, and bulk actions",
    category: "page",
    page: "Management",
    route: "/economy",
    keywords: ["economy", "coins", "transactions", "balance", "money"],
    iconName: "Coins",
    requiredLevel: "mod",
  },
  {
    id: "page-rooms",
    title: "Private Rooms",
    description: "Manage private voice room channels",
    category: "page",
    page: "Management",
    route: "/rooms",
    keywords: ["rooms", "private", "voice", "channels", "rent"],
    iconName: "DoorOpen",
    requiredLevel: "mod",
  },
  {
    id: "page-settings",
    title: "Settings",
    description: "All server configuration in one place",
    category: "page",
    page: "Configuration",
    route: "/settings",
    keywords: ["settings", "config", "configure", "options", "preferences"],
    iconName: "Settings",
    requiredLevel: "admin",
  },
  {
    id: "page-ranks",
    title: "Ranks",
    description: "Rank editor with thresholds and rewards",
    category: "page",
    page: "Configuration",
    route: "/ranks",
    keywords: ["ranks", "levels", "xp", "progression", "leaderboard"],
    iconName: "Trophy",
    requiredLevel: "admin",
  },
  {
    id: "page-shop",
    title: "Shop",
    // --- AI-MODIFIED (2026-03-23) ---
    // Purpose: Shop is now accessible to all members, not just admins
    description: "Browse and manage shop items",
    category: "page",
    page: "Overview",
    route: "/shop",
    keywords: ["shop", "store", "items", "buy", "purchase", "price", "colour", "room", "rental"],
    iconName: "ShoppingBag",
    // --- END AI-MODIFIED ---
  },
  // --- AI-MODIFIED (2026-03-23) ---
  // Purpose: Leaderboard config page in search registry
  {
    id: "page-leaderboard-config",
    title: "Leaderboard",
    description: "Season, unranked roles, and role filtering",
    category: "page",
    page: "Configuration",
    route: "/leaderboard",
    keywords: ["leaderboard", "season", "unranked", "filter", "role", "ranking"],
    iconName: "BarChart3",
    requiredLevel: "admin",
  },
  // --- END AI-MODIFIED ---
  {
    id: "page-rolemenus",
    title: "Role Menus",
    description: "Reaction role menus and self-assign roles",
    category: "page",
    page: "Configuration",
    route: "/rolemenus",
    keywords: ["role", "menu", "reaction", "self-assign", "selector"],
    iconName: "ListChecks",
    requiredLevel: "admin",
  },
  {
    id: "page-liongotchi",
    title: "Pet Settings",
    description: "LionGotchi virtual pet configuration",
    category: "page",
    page: "Configuration",
    route: "/liongotchi",
    keywords: ["pet", "liongotchi", "virtual", "gotchi", "drops"],
    iconName: "PawPrint",
    requiredLevel: "admin",
  },
  {
    id: "page-schedule",
    title: "Schedule",
    description: "Accountability session scheduling",
    category: "page",
    page: "Features",
    route: "/schedule",
    keywords: ["schedule", "session", "accountability", "booking", "group"],
    iconName: "Calendar",
    requiredLevel: "admin",
  },
  {
    id: "page-pomodoro",
    title: "Pomodoro",
    description: "Pomodoro timer configuration and stats",
    category: "page",
    page: "Features",
    route: "/pomodoro",
    keywords: ["pomodoro", "timer", "focus", "break", "tomato"],
    iconName: "Timer",
    requiredLevel: "admin",
  },
  {
    id: "page-videochannels",
    title: "Video Channels",
    description: "Video-required channel enforcement",
    category: "page",
    page: "Features",
    route: "/videochannels",
    keywords: ["video", "camera", "channels", "enforcement", "webcam"],
    iconName: "Video",
    requiredLevel: "admin",
  },
  {
    id: "page-setup",
    title: "Setup Wizard",
    description: "Guided server setup walkthrough",
    category: "page",
    page: "Features",
    route: "/setup",
    keywords: ["setup", "wizard", "onboarding", "getting started", "configure"],
    iconName: "Wand2",
    requiredLevel: "admin",
  },
  {
    id: "page-branding",
    title: "Branding",
    description: "Customize card colors and themes",
    category: "page",
    page: "Premium",
    route: "/branding",
    keywords: ["branding", "colors", "theme", "skin", "customize", "design"],
    iconName: "Paintbrush",
    requiredLevel: "admin",
    premium: true,
  },
  {
    id: "page-leaderboard-autopost",
    title: "Leaderboard Auto-Post",
    description: "Scheduled leaderboard posting",
    category: "page",
    page: "Premium",
    route: "/leaderboard-autopost",
    keywords: ["leaderboard", "auto", "post", "schedule", "recurring"],
    iconName: "Trophy",
    requiredLevel: "admin",
    premium: true,
  },
  {
    id: "page-ambient-sounds",
    title: "Ambient Sounds",
    description: "Background audio in voice channels",
    category: "page",
    page: "Premium",
    route: "/ambient-sounds",
    keywords: ["ambient", "sounds", "music", "rain", "noise", "audio", "white noise", "background"],
    iconName: "Volume2",
    requiredLevel: "admin",
    premium: true,
  },
  {
    id: "page-sticky-messages",
    title: "Sticky Messages",
    description: "Auto-reposted pinned messages",
    category: "page",
    page: "Premium",
    route: "/sticky-messages",
    keywords: ["sticky", "pin", "message", "repost", "persistent"],
    iconName: "Pin",
    requiredLevel: "admin",
    premium: true,
  },
]

const SETTINGS_SECTION_ITEMS: SearchItem[] = [
  {
    id: "setting-study-rewards",
    title: "Study Rewards",
    description: "Hourly reward, camera bonus, daily study cap",
    category: "setting",
    page: "Settings",
    route: "/settings",
    section: "study-rewards",
    keywords: ["study", "reward", "hourly", "voice", "camera", "bonus", "cap", "coins per hour"],
    iconName: "BookOpen",
    requiredLevel: "admin",
  },
  {
    id: "setting-economy",
    title: "Economy Settings",
    description: "Starting coins, transfers, coins per XP",
    category: "setting",
    page: "Settings",
    route: "/settings",
    section: "economy",
    keywords: ["economy", "coins", "transfer", "xp", "starting", "funds", "balance"],
    iconName: "Coins",
    requiredLevel: "admin",
  },
  {
    id: "setting-tasks",
    title: "Task Settings",
    description: "Max tasks, task reward, daily reward limit",
    category: "setting",
    page: "Settings",
    route: "/settings",
    section: "tasks",
    keywords: ["task", "todo", "reward", "limit", "max tasks", "checklist"],
    iconName: "CheckSquare",
    requiredLevel: "admin",
  },
  {
    id: "setting-rooms",
    title: "Private Room Settings",
    description: "Rent price, capacity, visibility, cooldown",
    category: "setting",
    page: "Settings",
    route: "/settings",
    section: "rooms",
    keywords: ["room", "rent", "private", "visible", "cooldown", "auto-extend", "deposit", "capacity"],
    iconName: "Lock",
    requiredLevel: "admin",
  },
  {
    id: "setting-schedule",
    title: "Accountability Settings",
    description: "Booking cost, attendance reward, group bonus",
    category: "setting",
    page: "Settings",
    route: "/settings",
    section: "schedule",
    keywords: ["schedule", "session", "booking", "accountability", "attendance", "group bonus"],
    iconName: "Users",
    requiredLevel: "admin",
  },
  {
    id: "setting-ranks",
    title: "Rank Settings",
    description: "Rank type, DM rank-ups, XP per period",
    category: "setting",
    page: "Settings",
    route: "/settings",
    section: "ranks",
    keywords: ["rank", "level", "xp", "leaderboard", "dm", "rank-up", "progression"],
    iconName: "Trophy",
    requiredLevel: "admin",
  },
  {
    id: "setting-moderation",
    title: "Moderation Settings",
    description: "Video study ban, camera grace period, persist roles",
    category: "setting",
    page: "Settings",
    route: "/settings",
    section: "moderation",
    keywords: ["video", "ban", "moderate", "roles", "grace", "persist", "study ban"],
    iconName: "Shield",
    requiredLevel: "admin",
  },
  {
    id: "setting-general",
    title: "General Settings",
    description: "Timezone, language, locale",
    category: "setting",
    page: "Settings",
    route: "/settings",
    section: "general",
    keywords: ["timezone", "language", "locale", "region", "time zone"],
    iconName: "Globe",
    requiredLevel: "admin",
  },
  {
    id: "setting-welcome",
    title: "Welcome Messages",
    description: "Greeting channel, welcome and returning messages",
    category: "setting",
    page: "Settings",
    route: "/settings",
    section: "welcome",
    keywords: ["welcome", "greeting", "returning", "message", "join", "hello"],
    iconName: "MessageSquare",
    requiredLevel: "admin",
  },
  {
    id: "setting-workouts",
    title: "Workout Settings",
    description: "Minimum length, workout reward",
    category: "setting",
    page: "Settings",
    route: "/settings",
    section: "workouts",
    keywords: ["workout", "exercise", "fitness", "gym", "minimum length"],
    iconName: "Dumbbell",
    requiredLevel: "admin",
  },
  {
    id: "setting-channels",
    title: "Channel Settings",
    description: "Event log, mod log, alert, and pomodoro channels",
    category: "setting",
    page: "Settings",
    route: "/settings",
    section: "channels",
    keywords: ["channel", "log", "event", "alert", "greeting", "notification"],
    iconName: "Hash",
    requiredLevel: "admin",
  },
  {
    id: "setting-roles",
    title: "Role Settings",
    description: "Admin role, moderator role assignments",
    category: "setting",
    page: "Settings",
    route: "/settings",
    section: "roles",
    keywords: ["role", "admin", "moderator", "permission", "staff"],
    iconName: "UserCog",
    requiredLevel: "admin",
  },
  {
    id: "setting-tracking",
    title: "Tracking Exclusions",
    description: "Channels excluded from study and XP tracking",
    category: "setting",
    page: "Settings",
    route: "/settings",
    section: "tracking",
    keywords: ["untracked", "tracking", "exclude", "ignore", "voice channels", "text channels"],
    iconName: "EyeOff",
    requiredLevel: "admin",
  },
  {
    id: "setting-autoroles",
    title: "Auto-Roles",
    description: "Roles automatically assigned to new members and bots",
    category: "setting",
    page: "Settings",
    route: "/settings",
    section: "autoroles",
    keywords: ["autorole", "auto", "join", "new member", "bot", "automatic"],
    iconName: "Bot",
    requiredLevel: "admin",
  },
  // --- AI-MODIFIED (2026-03-23) ---
  // Purpose: Moved leaderboard settings from Settings to dedicated Leaderboard page
  {
    id: "setting-statistics",
    title: "Season & Leaderboard",
    description: "Season start, unranked roles, role filtering",
    category: "setting",
    page: "Leaderboard",
    route: "/leaderboard",
    keywords: ["season", "stats", "leaderboard", "unranked", "filter", "role", "ranking"],
    iconName: "BarChart3",
    requiredLevel: "admin",
  },
  {
    id: "setting-role-filter",
    title: "Leaderboard Role Filter",
    description: "Let users filter /leaderboard by role",
    category: "setting",
    page: "Leaderboard",
    route: "/leaderboard",
    keywords: ["filter", "role", "leaderboard", "dropdown"],
    iconName: "Filter",
    requiredLevel: "admin",
  },
  // --- END AI-MODIFIED ---
  {
    id: "setting-danger",
    title: "Danger Zone",
    description: "Reset season or reset all settings",
    category: "setting",
    page: "Settings",
    route: "/settings",
    section: "danger",
    keywords: ["reset", "danger", "delete", "clear", "wipe"],
    iconName: "AlertTriangle",
    requiredLevel: "admin",
  },
]

const FEATURE_ITEMS: SearchItem[] = [
  {
    id: "feature-pomodoro-timers",
    title: "Pomodoro Timers",
    description: "Configure individual timer channels and durations",
    category: "feature",
    page: "Pomodoro",
    route: "/pomodoro",
    keywords: ["timer", "pomodoro", "focus", "break", "duration", "channel", "voice"],
    iconName: "Timer",
    requiredLevel: "admin",
  },
  {
    id: "feature-pomodoro-focus-role",
    title: "Focus Role",
    description: "Role assigned during focus sessions",
    category: "feature",
    page: "Pomodoro",
    route: "/pomodoro",
    keywords: ["focus", "role", "pomodoro", "studying", "active"],
    iconName: "Timer",
    requiredLevel: "admin",
  },
  {
    id: "feature-pomodoro-summaries",
    title: "Session Summaries",
    description: "Automatic study session summary messages",
    category: "feature",
    page: "Pomodoro",
    route: "/pomodoro",
    keywords: ["summary", "session", "pomodoro", "notification", "recap"],
    iconName: "Timer",
    requiredLevel: "admin",
  },
  {
    id: "feature-schedule-channels",
    title: "Schedule Channels",
    description: "Lobby, session room, and voice channels for scheduling",
    category: "feature",
    page: "Schedule",
    route: "/schedule",
    keywords: ["schedule", "lobby", "session", "voice", "channel", "room"],
    iconName: "Calendar",
    requiredLevel: "admin",
  },
  {
    id: "feature-schedule-attendance",
    title: "Attendance Rules",
    description: "Minimum attendance, blacklist role, miss limits",
    category: "feature",
    page: "Schedule",
    route: "/schedule",
    keywords: ["attendance", "blacklist", "miss", "absent", "minimum", "schedule"],
    iconName: "Calendar",
    requiredLevel: "admin",
  },
  {
    id: "feature-video-enforcement",
    title: "Video Enforcement",
    description: "Grace period, study-ban role, duration ladder",
    category: "feature",
    page: "Video Channels",
    route: "/videochannels",
    keywords: ["video", "enforcement", "grace", "study-ban", "camera", "duration", "ladder"],
    iconName: "Video",
    requiredLevel: "admin",
  },
  {
    id: "feature-video-exempt",
    title: "Video Exempt Roles",
    description: "Roles exempt from video requirements",
    category: "feature",
    page: "Video Channels",
    route: "/videochannels",
    keywords: ["exempt", "video", "role", "skip", "bypass"],
    iconName: "Video",
    requiredLevel: "admin",
  },
  {
    id: "feature-branding-cards",
    title: "Card Customization",
    description: "Customize profile, stats, and leaderboard card colors",
    category: "feature",
    page: "Branding",
    route: "/branding",
    keywords: ["card", "color", "customize", "profile", "stats", "leaderboard", "theme", "skin"],
    iconName: "Paintbrush",
    requiredLevel: "admin",
    premium: true,
  },
  {
    id: "feature-autopost-schedule",
    title: "Auto-Post Schedule",
    description: "When and how often leaderboards are posted",
    category: "feature",
    page: "Leaderboard Auto-Post",
    route: "/leaderboard-autopost",
    keywords: ["schedule", "recurring", "cron", "interval", "auto-post", "leaderboard"],
    iconName: "Trophy",
    requiredLevel: "admin",
    premium: true,
  },
  {
    id: "feature-autopost-rewards",
    title: "Auto-Post Rewards",
    description: "Coin rewards for leaderboard top positions",
    category: "feature",
    page: "Leaderboard Auto-Post",
    route: "/leaderboard-autopost",
    keywords: ["reward", "coins", "prize", "top", "leaderboard", "auto-post"],
    iconName: "Trophy",
    requiredLevel: "admin",
    premium: true,
  },
  {
    id: "feature-ambient-bots",
    title: "Ambient Sound Bots",
    description: "Configure up to 5 sound bot slots",
    category: "feature",
    page: "Ambient Sounds",
    route: "/ambient-sounds",
    keywords: ["ambient", "sound", "bot", "slot", "rain", "noise", "volume", "campfire"],
    iconName: "Volume2",
    requiredLevel: "admin",
    premium: true,
  },
  {
    id: "feature-sticky-editor",
    title: "Sticky Message Editor",
    description: "Channel, content, embed color, repost interval",
    category: "feature",
    page: "Sticky Messages",
    route: "/sticky-messages",
    keywords: ["sticky", "embed", "channel", "content", "repost", "interval", "color"],
    iconName: "Pin",
    requiredLevel: "admin",
    premium: true,
  },
  {
    id: "feature-liongotchi-drops",
    title: "Pet Drop Notifications",
    description: "Drop channel and auto-delete settings",
    category: "feature",
    page: "Pet Settings",
    route: "/liongotchi",
    keywords: ["pet", "drop", "notification", "channel", "auto-delete", "liongotchi"],
    iconName: "PawPrint",
    requiredLevel: "admin",
  },
  {
    id: "feature-liongotchi-access",
    title: "Pet Activity & Access",
    description: "Activity-only role and teaser toggle",
    category: "feature",
    page: "Pet Settings",
    route: "/liongotchi",
    keywords: ["pet", "activity", "role", "teaser", "access", "liongotchi"],
    iconName: "PawPrint",
    requiredLevel: "admin",
  },
]

const ALL_ITEMS: SearchItem[] = [
  ...PAGE_ITEMS,
  ...SETTINGS_SECTION_ITEMS,
  ...FEATURE_ITEMS,
]

export function getSearchItems(isAdmin: boolean, isMod: boolean): SearchItem[] {
  return ALL_ITEMS.filter((item) => {
    if (item.requiredLevel === "admin" && !isAdmin) return false
    if (item.requiredLevel === "mod" && !isMod && !isAdmin) return false
    return true
  })
}
